model:
  n_emb: 384
  num_heads: 6
  head_dim: 256
  n_layers: 10
  dropout: 0.3
  
training:
  batch_size: 64
  lr: 0.0003
  iterations: 6000
  train: True
  eval_iters: 100
  eval_interval: 200
  train_model: GPT
  compile: False

dataset:
  train_split: 0.9
  fname: dataset/input.txt
  vocab_size: 65

# inference 
inference:
  max_new_tokens: 500

general:
  log: INFO
  block_size: 256
  save_ckpt: weights
